DROP TABLE user IF EXISTS;

create table user (
    id bigint generated by default as identity,
    name varchar(255) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    phone_number varchar(255),
    primary key (id)
);

DROP TABLE role IF EXISTS;

create table role (
    id bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

DROP TABLE privilege IF EXISTS;

create table privilege (
    id bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

DROP TABLE user_role IF EXISTS;

create table user_role (
    user_id bigint,
    role_id bigint,
    primary key (user_id, role_id),
    foreign key (user_id) references user(id),
    foreign key (role_id) references role(id)
);

DROP TABLE role_privileage IF EXISTS;

create table role_privilege (
    role_id bigint not null,
    privilege_id bigint not null,
    primary key (role_id, privilege_id),
    foreign key (role_id) references role(id),
    foreign key (privilege_id) references privilege(id)
);